@startuml
skinparam packageStyle rectangle
left to right direction

actor user

rectangle pi-control {
  user --> (authenticate)
  user --> (add command)
  user --> (edit command)
  user --> (execute command)
  user --> (remove command)
}
@enduml
