@startuml
skinparam packageStyle rectangle
left to right direction

actor user

rectangle Storage-Manager {
  user --> (Add Item to Storage)
  user --> (Remove Item from Storage)
  user --> (check expiring products)
  user --> (check how long the stock lasts for the community of needs)
  user --> (invite people to own community of needs)
@enduml
